name: bringo
description: A new Flutter project

publish_to: 'none' # Remove this if you want to publish
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  material_color_utilities: 0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: 2.1.4

flutter:
  uses-material-design: true
